---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Concatenate to existing dotfiles
  lineinfile:
    dest: "{{ dotfiles_home }}/{{ item }}"
    line: "{{ lookup('file', '{{ dotfiles_repo_local_destination }}/{{ item }}') }}"
    backup: true
    create: true
  with_items: "{{ existing_dotfiles }}"

- name: Copy new dotfiles
  copy:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    force: true
  with_items:
    "{{ new_dotfiles }}"
